version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: stock-data-web
    container_name: stock-data-web
    ports:
      - "5005:5000"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: "1"